2339630	Where is the picture taken?	A ina aka ɗauki hoton?
2329507	When was this picture taken?	Da yaushe aka ɗauki wannan hoton?
2414273	Where is the cat?	Ina magen?
2414273	What animal is shown?	Wacce dabba aka nuna?
2382461	What are the people doing?	Me mutanan ke yi?
2320382	What is pictured?	Me aka ɗauka?
2415200	What does the sign say?	Me alama take cewa?
2319464	What is this?	Mene wannan?
2415249	What is the girl watching on TV?	Me yarinyar ke kalla a talabiji?
2368396	What kind of road?	Wanne irin titi ne?
2372746	Who is flying over the water?	Wake tsallake ruwa?
2368783	How much facial hair does the man have?	Gashin fuska nawa yake dashi?
2386677	Where is the bench?	Ina benci.
2405971	How many sandwiches are there?	Sandwic nawa ne a nan?
2372365	What is in the man's right hand?	Mene ne a hannun daman mutumin?
2386677	What is in front of the toilet?	Mene a gaban masai banɗaki.
2405971	How many sandwiches are in the photo?	Sandwic bawa ne a hoton?
2390856	What is the boat creating?	Me jirgin ruwa yake yi?
2358256	What is the man doing?	Me mutumin ke yi?
2335740	When was the photo taken?	A yaushe aka ɗauki hoton?
2390724	What is on the plate?	Mene akan farantin?
2349179	Where was the picture taken?	A ina aka ɗauki hoton?
2360697	What shade of color is the plate?	Wanne irin launin faranti ne?
2360697	What is that on the plate?	Mene akan farantin?
2321088	Where was the picture taken?	A ina aka ɗauki hoton.
2409343	What does the plane say?	Me aka rubuta a jikin jirgin saman?
2409343	Where was the photo taken?	A ina aka ɗauki hoton?
2409296	What color is the Helmet?	Mene launin hular kwanon?
2372533	What amount of tracks?	Hanyar jirgin ƙasan nawa ne?
2360550	Where on Steiner Street is this location?	Ina ne nan a titin steiner ?
2393819	What is in the park?	Mene ne lambun?
2393819	What is black and leather?	Mene ne baƙi kuma na fata?
2345475	What color is the snow?	Mene ne launin dusar ƙanƙara?
2403065	What is the man standing on?	Akan me mutumin ke tsaye?
2388563	Why the ground is muddy?	Meyasa ƙasan yayi taɓo?
2412517	What is in the tray?	Mene a tire din?
2404836	What is the sitting man wearing?	Me mutumin dake zaune yake sanye dashi?
2405531	How many elephants are shown?	Giwayen nawa aka nuna?
2373259	What are the kids eating?	Me yaran suke ci?
2373259	What shape is the table?	Yaya siffar tebur din yake?
2392531	What is on the top of the train?	Mene ne a saman jirgin ƙasan?
2334649	Where are the giraffes looking?	Ina raƙumin dawan ke kalla?
2408118	What color is the advertisement?	Mene ne launin tallar?
2402563	When was this taken?	Da yaushe aka ɗauki wannan hoton?
2405608	Who owns the railway?	Waye ke da mallakin tashar jirgin ƙasan?
2385208	Where was the picture taken?	A ina aka ɗauki hoton?
2385208	What color is the table?	Mene ne launin tebur din?
2350133	What color is the water?	Meye launin ruwan?
2409318	What is in the air?	Mene a iska?
2347287	What color is the cat?	Menene launin magen?
2360978	What does the black and gold sign say?	Me aka rubuta a jikin baƙi da ruwan kwal din alamar?
2376409	What color is the sign text?	Mene launin rubuta dake jikin alamar
2371578	What is the woman in white walking?	Me matar dake sanye da farar riga ke ja?
2411204	How many phones are in the picture?	Wayar salula nawa ne a hoton?
2342457	When is this scene taking place?	Yaushe wannan abun ya faru?
2342457	Where is the cow?	Ina saniyar?
2377693	How many men are there?	Maza nawa ne a nan.
2370651	What is the man playing?	Wasan me mutumin yake?
2330337	Where is the fence?	Ina dangar?
2335740	What time of day is it?	Wanne lokaci ne wannan?
2417901	What color is the nearest table?	Mene launin tebur din dake kusa?
2359237	How does the sky look?	Yaya sararin samaniya yake?
2366911	What does the yellow light mean?	Me rawayan fitila ke nufi?
2381185	What country's flag is here?	Wacce tutar ƙasa ce a nan?
2409594	What color is the outfit?	Wanne launin kayan sawa ne?
2366011	What is the zebra doing?	Me jakin dawan yake yi?
2328845	Who is on the ground?	Suwaye a ƙasa?
2372533	What is on the track?	Mene a kan hanya?
2396897	What does the guy have on his head?	Me mutumin ke dashi a kansa?
2345475	How many people are there?	Mutane ne nawa a nan?
2317967	What color is the sky?	Mene launin sararin samaniya?
2394499	What design is on the hat band?	Ya zanan jikin hular yake?
2316709	When is the boat in the water?	A wanne lokaci jirgin ruwa yake cikin ruwan?
2414268	What number is on the train?	Wacce lamba ce a jikin jirgin ƙasan?
2407844	How many men?	Maza nawa ne?
2378502	What time of day is it?	Wanne lokaci ne wannan?
2407334	What are the giraffes doing?	Me raƙuman dawa yake yi?
2316213	Who is pictured?	Waye a hoton?
2341475	What is the man riding on?	Me mutumin yake tukawa?
2353804	What color is the man in front's hat?	Wani launi ne da hular mutumin dake gaba?
2338525	Who is there?	Waye a gurin?
2315483	What color is the sky?	Wani launi ne da saman?
2360089	What can be seen outside the window?	Menene ake iya gani a wajen tagar?
2367820	What is on the windows of the red building on the right?	Menene a jikin tagogin jan ginin dake dama?
2325181	Who is under the clock?	Waye a ƙasan agogon?
2325181	When was this taken?	Yaushe aka ɗauka hoton?
2362072	What is the number of people in the photo?	Menene adadin mutane a cikin hoton?
2370667	What type of animal?	Wani irin dabba?
2340962	What is on either side of the bench?	Menene a kowani gefen bencin?
2339853	What is the black ring shaped food?	Wani abinci ne baƙi mai siffar zobe?
2333612	How many bottles of beer are there?	Nawane adadin kwalaben giya a gurin?
2380059	How is the bread served?	Ta yaya aka samar da biredin?
2416233	What color is the dog?	Wani launi ne da karen?
2346599	How many bears are there?	Nawane adadin bears a gurin?
2406154	Where is the man standing?	A ina mutumin yake tsaye?
2374396	What is the walkway made of?	Dame akayi wajan tafiyar?
2360541	Where are the man's socks?	Ina safar mutumin?
2372365	What is the man holding?	Me mutumin yake riƙe dashi.
2330337	When was this photo taken?	Da yaushe aka ɗauki wannan hoton?
2390856	What color is the water?	Mene launin ruwan nan?
2377924	What item is used for shade?	Me ake amfani dashi dan samun inuwa.
2377924	Who is holding a umbrella?	Waye ya riƙe da lema.
2417901	What is the nearest little boy doing?	Me ƙaramin yaro mafi kusan yake yi?
2406916	Where is tree?	Ina bishiya?
2355345	Where is the game being played?	A ina ake yin wasan?
2409343	How many planes are there?	Nawane adadin jiragen sama a gurin?
2384565	What color is cabinet?	Wani launi ne da durowar?
2372365	Where is the man?	Ina mutumin?
2328205	When is the picture taken?	Yaushe aka ɗauka hoton?
2362098	What is written on board?	Me aka rubuta a jikin allon?
2390856	Where is the man?	Ina mutumin?
2362098	What does the sign say?	Me alamar ta ce?
2409296	Where are the people?	Ina mutanen?
2392556	What is in the man's hand?	Menene a hannun mutumin?
2417901	What color is the dress of the girl nearest?	Wani launi ne da rigar yarinya mafi kusan?
2373710	What is in the left hand?	Menene a hannun hagun?
2368296	What is the lamp doing?	Me fitilar take yi?
2381488	When is this picture taken?	Yaushe aka ɗauka hoton?
2366911	What kind of car is in the driveway?	Wacce irin mota ce a kan titin?
2396897	What is brown and wooden?	Menene ruwan ƙasa kuma na katako?
2414610	What color is the rackets handle?	Wani launi ne da mariƙin raket ɗin?
2406916	What types of suits are the people wearing?	Wasu irin kwat mutanen suke sake da shi
2342468	What color is the snow?	Wani launi ne da dusar ƙanƙarar?
2393293	Where is the elephant?	Ina giwar?
2406991	Where is the Frisbee?	Ina Frisbee ɗin?
2406991	What color is the grass?	Wani launi ne da ciyawar?
2398981	Where is the picture taken?	A ina aka ɗauka hoton?
2409594	When is this guy going to?	Yaushe wannan gayen zaije?
2390724	What is decorating the plate?	Menene ya ƙawata farantin?
2414305	What is in the background?	Mene a kasan bayan hoton?
2365424	Where is the girl?	Ina yarinyar?
2405531	How many legs does the elephant have?	Ƙafa nawa giwar take dashi?
2401712	What is the main color of the nostrils?	Mene ainihi launin ƙofar hancin su?
2384565	What color is cat?	Mene launin magen?
2407334	What color is the wood wall?	Mene launin bangar katako?
2407969	Where is light coming from?	Ta Ina haske yake fitowa?
2353804	When was the picture taken?	Yaushe aka ɗauki hoton?
2351388	Where is a shadow?	Ina inuwar take?
2351388	What color is the grass?	Mene launin ciyawar?
2372104	When was the photo taken?	Da yaushe aka ɗauki wannan hoton?
2390545	How does the food taste?	Yaya ɗanɗanon abincin?
2342718	How many truck parked?	Nawane adadin babbar mota da aka ajiye?
2362072	What are the people looking at?	Me mutanen suke kallo?
2385208	What is in the glass?	Menene a cikin kofin gilashin?
2370651	Why is the man holding a baseball mitt?	Meyasa mutumin yake riƙe da safar hannun baseball?
2373171	What is the woman holding?	Me matar take riƙe dashi?
2408066	What color is the shirt of the child?	Wani launi ne da rigar yarinyar?
2337267	Where is the man standing?	A ina mutumin yake tsaye?
2347694	What is in the doorway?	Menene a hanyar ƙofar?
2330337	What animal is there?	Wacce dabba ce a nan?
2417947	What is on the mountain?	Menene a kan dutsen?
2345905	What is the woman in the green dress holding?	Me matar dake sanye da koren kaya take riƙe dashi?
2334064	When was the picture taken?	A yaushe aka ɗauki hoton?
2370667	How is the dog positioned?	Yaya yanayin karen yake?
2345475	What gender is the person?	Mene jinsin mutumin?
2370667	What color is the dog?	Mene launin karen?
2406916	What color is the man's suit?	Mene launin kwat din mutumin?
2370667	What type of animal?	Wacce irin dabba ce ?
2406916	What is behind the woman?	Mene a bayan matar?
2394499	What color is the dog's nose?	Mene launin hancin karen?
2381185	Why is the flag slack?	Meyasa tutar ke kwance?
2340962	When was this picture taken?	Da yaushe aka ɗauki wannan hoton?
2355345	How many men on the tennis court?	Mutane nawa ne a filin tanis din?
2382489	What animal is laying in the grass?	Wanne irin dabba ce ke kwance a cikin ciyawar?
2349179	What color is a helmet?	Mene launin hular kwanon?
2409318	What is the man riding?	Me mutumin ke tuƙawa?
2324028	What is lit?	Mene a kunne?
2388563	What is blue in the picture?	Mene shuɗi a hoton?
2393420	Where is the pair of shoes?	Ina takalman.
2321088	How many people are there?	Mutane nawa a nan?
2401976	What type of seating is shown?	Wanne irin abin zama aka nuna?
2410132	Why is the grass green?	Meyasa ciyawar ta zama Koriya?
2384565	Where cat laying?	A ina magen ke kwance?
2399016	Where are the bananas?	A ina ayaba take?
2328205	What are the zebra doing?	Me jakunan dawan suke yi?
2416233	What material is couch based on?	Da wanne abu akayi kungiya.
2386549	Who is taking care of the plane?	Waye ke  kula da jirgin saman?
2328845	When is person using hammer?	A yaushe mutumin yake anfani da gudumar?
2377693	Who is wearing a blue helmet?	Waye ke sanye da shuɗiyar hular kwano
2406164	Where is the bridge?	Ina gadar?
2366573	What is the dog doing in the picture?	Ke karen ke yi a hoton?
2353804	How many people are there?	Mutane nawa ne a nan?
2417947	What is in the background?	Mene a kasan bayan hoton?
2417947	Where is the skier?	Ina mai wasan hawa ƙanƙara?
2338525	How is he looking?	Yaya kuke ganin shi?
2323147	Why is the ground wet?	Meyasa ƙasan ya jike?
2319992	How many people are in this picture?	Mutane nawa ne a hoton?
2410341	What is the table made of?	Dame akayi tebur din?
2332518	What color is the grass?	Mene launin ciyawar?
2364899	What is red and has an engine?	Mene Ja kuma yake da inji?
2414610	Where is the ball?	Ina kwallon yake?
2334649	How many animals are shown?	Dabbobi nawa aka nuna?
2367820	What is the gender of the person shown?	Mene ne jinsin mutumin da aka nuna?
2389530	Where is this pizza?	Ina wannan fiza?
2340549	What color is the fence?	Menene launin dangar?
2393733	What is on the back table?	Mene ne akan tebur din baya?
2405644	What color is the sky?	Mene launin sararin samaniya?
2337267	What is in the sky?	Mene a sararin samaniya?
2401685	What kind of drink is the man on the right holding?	Wanne irin abun sha mutumin dake hannun dama yake riƙe dashi?
2402676	How many balls?	Kwallon nawa ne?
2341155	When was the picture taken?	A yaushe aka ɗauki hoton?
2392157	What type of building is behind the bus?	Wanne irin gini ne a bayan motar bas din?
2336062	What is blue and white?	Mene ne mai shuɗi da fari?
2336062	What is black and brown?	Mene baƙi kuma mai ruwan ƙasa?
2408084	What color is the man's helmet?	Mene launin hular kwanon mutumin
2388563	What is made of wood?	Mene aka yi da katako?
2360686	What color is the player's helmet?	Mene launin hular kwanon mutumin?
2388563	When was the picture taken?	Da yaushe aka ɗauki hoton?
2360686	What game is being played?	Wanne wasa ake yi?
2409318	What color is the helmet?	Mene launin hular kwanon sa?
2360541	Where is the man sleeping?	A ina mutumin ke barci
2323147	How many arrow signs?	Alamun mashi guda nawa ne?
2363917	Where was the picture taken?	A ina aka ɗauki hoton?
2363917	When was this picture taken?	Yaushe aka ɗauki wannan hoton?
2366157	Where is the man?	Ina mutumin yake?
2408118	What is man wearing?	Me mutumin ke sanye dashi?
2368217	What is the grey object in the front of the picture?	Mene ne mai launin ruwan toka dake gaban hoton
2371578	What is the fence made of?	Dame akayi shingen?
2328685	How many cups are shown?	Moɗa nawa aka nuna?
2378308	"What color light is lit up	 on the bottom?"
2340962	Who was the bench dedicated to?	Zuwa ga wa aka kaddamar ga bencin?
2350133	Where is the bird?	Ina tsuntsu?
2405069	Where are the plants?	Ina shuka?
2363898	Where was the picture taken?	A ina aka ɗauki hoton?
2363898	When was the picture taken?	A yaushe aka ɗauki hoton?
2409318	What is the man doing?	Me mutumin ke yi?
2342457	What color is the cow?	Mene launin san?
2368217	Where are white clouds?	Ina fararan gizagizan?
2322820	Where is the cow?	Ina san?
2410402	Who is walking in the water?	Waye yake tafiya cikin ruwa?
2409678	What kind of decorations are on the cake?	Wanne irin ado ne akan kek din?
2372365	What is the woman doing in the background?	Me matar dake ƙasan bayan hoton take yi?
2330616	What is the woman holding in her hand?	Me matar ke riƙe dashi a hannun ta?
2386985	What is on top of the bus?	Mene a saman motar bas din?
2335297	Where was this photo taken?	A ina aka ɗauki wannan hoton?
2337917	What color is the horse?	Mene launin dokin?
2333844	Where was this photo taken?	A ina aka ɗauki wannan hoton?
2381185	What street number is here?	Mene lambar titin nan?
2409594	What color is the jacket?	Mene launin rigar ?
2349179	How many people are in the photo?	Mutane nawa ne a hoton?
2372034	Where is the knife?	Ina wuƙar?
2330938	Where are the people?	Ina mutanen?
2323235	What is in the hand of the girl?	Mene a hannun yarinyar?
2328205	What animal is seen?	Wacce dabba ake gani?
2390545	How many pieces of cake are shown?	ɓangaren kek nawa aka nuna?
2373710	What time is it?	Wanne lokaci wannan?
2368296	What animal is shown?	Wacce dabba aka nuna?
2368296	How are the cat's eyes?	Yaya idanun magen?
2335167	Where is the clock?	Ina agogon?
2317967	When was this photo taken?	Yaushe aka ɗauki wannan din.
2317967	What is on the man's head?	Mene akan mutumin?
2346896	What color is the kids umbrella?	Mene launin lemar mutumin
2316709	How many boats are there?	Jirgin ruwa nawa ne a nan?
2403065	How is the sky?	Yaya sararin samaniya yake
2405085	How is the horse colored?	Yaya launin dokin yake?
2414305	What is open on the man?	Mene a bude jikin mutumin?
2315483	How many signs are there?	Alamomi nawa ne a nan?
2325181	What time is it?	Ƙarfe nawa?
2362072	Where is the blue blanket?	Ina shuɗin mayafin rufar yake?
2402563	What is on the building?	Mene ne a jikin ginin?
2385208	What is the table made of?	Dame aka yi tebur din?
2347694	Where was this taken?	A ina aka ɗauki wannan?
2325217	Who is riding a horse?	Waye ke hawan doki?
2382489	Where was this picture taken?	A ina aka ɗauki wannan hoton
2360686	What is on the right side of photo?	Mene a gefen daga daman hoton?
2339853	How many potatoes are there?	Dankalin turawa nawa ne a nan?
2363917	What is this a picture of?	Wannan hoton mene?
2391575	What is visible?	Me aka iya gani?
2391575	What is visible?	Me ake iya gani?
2401976	Where was this picture taken?	A ina aka ɗauki wannan hoton?
2328685	What kind of food is shown?	Wanne irin abinci aka nuna?
2328685	Where are the cups?	Ina moɗayen?
2416233	When was this photographed?	Da yaushe aka ɗauki wannan?
2406154	What is the man throwing?	Me mutumin yake wurgawa?
2360541	When was the picture taken?	Yaushe aka ɗauki hoton nan?
2371973	What is the color of the grass?	Mene launin ciyawar?
2337917	What color is the umbrella?	Mene launin lemar?
2337917	When was this picture taken?	Yaushe aka ɗauki wannan hoton?
2333844	When was this photo taken?	Da yaushe aka ɗauki wannan hoton?
2390724	What is the color of the plate?	Mene launin farantin?
2330938	What fruit is this?	Wanne abun marmari ne wannan?
2393112	What is green in this picture?	Mene mai launin kore a wannan hoton?
2362098	What is this a photo of?	Wannan hoton me ne?
2372533	What is on the track?	Mene kan hanyar jirgin?
2385089	How many planes are in the air?	Jiragen sama nawa ne a sama.
2406164	How many people are shown?	Mutane nawa ne suka fito?
2384900	What is on the chair?	Mene akan kujera?
2407844	When was this photo taken?	A yaushe aka ɗauki wannan hoton?
2407844	Where is the plane pointed?	Ina jirgin saman yake kalla?
2373768	What is on a white plate?	Mene akan farin faranti?
2373768	Where is the fork?	Ina cokali yatsu?
2378502	What is in the sheep's ears?	Mene a kunnan tumaki?
2386549	Where might this be?	Ina nan zai iya kasancewa?
2407969	What color is the wall?	Mene launin bangon?
2351388	Who has four legs?	Waye ke da ƙafa hudu?
2342608	When was this?	Wanne lokaci ce nan?
2350133	How many legs does the bird have?	ƙafa nawa tsuntsu ke dashi?
2363898	What color are the trees?	Mene launin bishiyun?
2407228	What is surrounding the water?	Mene yake kewaye da ruwan?
2401976	What type of body of water is shown?	Mene irin ruwa ne aka nuna?
2408925	What kind of floor is in the picture?	Wanne irin daɓe ƙasa ne a hoton?
2332812	What is the man poking the fruit with?	Dame mutumin ke huda abun marmarin?
2392157	What kind of bus is shown?	Wacce irin motar bas ce wannan?
2408084	When does the scene occur?	Yaushe hakan ke faruwa?
2371973	What is the sign?	Mene a allon alamar?
2358256	What has spread beautiful wings?	Mene ya bude kyawawan fikafikin sa.
2417901	What pattern is on the boy's shirt?	Wanne irin zane ne jikin rigar yaron.
2359237	What color is the boat?	Mene launin jirgin ruwan?
2333844	How many trains are in the photo?	Jirgin ƙasa nawa ne a hoton?
2381185	When is the photo taken?	Yaushe aka ɗauki wannan hoton?
2330938	How many pieces of fruit are there?	Kayan marmari nawa ne a nan?
2366937	What is behind the woman?	Mene a bayan matar?
2366937	Who is holding the knife?	Wake riƙe da wuka?
2385089	How many people appear in this picture?	Mutane nawa ne suka fito a wannan hoton?
2406164	What is the weather?	Ya yanayi garin yake?
2360550	What does the lit up sign mean?	Me alamar hasken take nufi?
2393819	Who is wearing jeans?	Waye yake sanye da wandon jins
2393819	What is the man wearing?	Me mutumin ke sanye dashi?
2345475	When was the photo taken?	Yaushe aka ɗauki hoton?
2317967	What is the man riding?	Me mutumin ke tuƙawa?
2377847	How many cars are shown?	Motoci nawa aka nuna?
2402676	What is the woman going to hit?	Me matar zata buga?
2341155	Who is on the blue motorcycle?	Waye akan shuɗin babur?
2388563	What is the bench made of?	Dame akayi bencin?
2321163	Who is in the photo?	Waye a jikin hoton?
2365173	What are on the feet of the man on the left?	Mene a ƙafar mutumin dake hagu?
2365173	What are the people standing under?	Me mutanan suke tsaye a karkashin?
2407334	How many colors are the giraffes?	Launin nawa ne jikin raƙumin dawa?
2316213	When is this?	Yaushe ne nan?
2341475	Where is the man riding at?	A ina mutumin yake tuƙi.
2353804	What color is the snow?	Mene launin dusar ƙanƙara?
2323147	How many people are standing in the street?	Mutane nawa ke tsaye a kan titi?
2332518	How many trains are there?	Jiragen ƙasa nawa ne a nan?
2357217	Where was this taken?	A ina aka ɗauki wannan?
2408118	What color is the lettering on the sign?	Mene launin harufan dake kan alamar?
2412909	What is on the person's head?	Menene a kan mutum ɗin?
2347694	What is the train number?	Mene lambar jirgin ƙasan?
2350133	How many birds can you see?	Nawane adadin tsuntsaye da kake iya gani?
2413449	What is next to the beds?	Mene kusa da gadon?
2413449	What type of material is the bunk bed made of?	Da wani irin abu akayi gado mai hawa biyun?
2407228	What is the last letter on the side of the boat?	Menene harafin ƙarshe a jikin gefen jirgin ruwan?
2324028	How many candles are there?	Nawane adadin kyandir a gurin?
2324028	How many people are in the picture?	Nawane adadin mutane a cikin hoton?
2393420	What is the microwave on?	A kan me na'urar ɗumame ta ke?
2393420	Where is the microwave?	Ina na'urar ɗumamen?
2391575	What color is the sign?	Wani launi ne da alamar?
2364367	What is in front of the woman?	Menene a gaban matar?
2328685	When is this type of food typically eaten?	Yaushe ake cin irin wannan abincin yawanci?
2411204	What is tihe girl holding?	Me yarinyar take riƙe dashi?
2363672	What is the road that starts with H?	Wacce hanya ce da ta fara da H?
2346599	When was this picture taken?	A yaushe aka ɗauki wannan hoton?
2340549	Where is this picture taken?	A ina aka ɗauka hoton?
2408925	What is the cat doing?	Me magen take yi?
2330616	What color are the leaves?	Wani launi ne da ganyanyakin?
2417707	Why is the person's hand up?	Meyasa mutumin ya daga hannun sa sama?
2335297	When was this photo taken?	Yaushe aka ɗauka hoton?
2330337	What color is the dirt?	Wani launi ne da dattin?
2330337	What color are the zebras?	Mene launin jakunan dawa?
2403741	What colour is the grass?	Wani launi ne da ciyawan?
2403741	What is green in the photo?	Mene kore a hoton?
2355345	What is the gender of the people playing tennis?	Menene jinsin mutanen da suke yin wasan tanis?
2406991	What color is the grass?	Wani launi ne da ciyawan?
2409594	What color is the mountain?	Wani launi ne da dutsen?
2404308	What is in the background?	Menene a bayan?
2365424	What is this bench made of?	Dame akayi bencin?
2384565	What is cat doing?	Me magen ke yi?
2328205	How many zebras?	Jakunan dawa nawa ne?
2348234	What is the color of the camera?	Mene launin kamera?
2385089	When was this picture taken?	Da yaushe aka ɗauki wannan hoton?
2360550	What street does the sign say?	Wanne alamar titi ne?
2335167	Why is it behind a line?	Meyasa yake bayan danga?
2393293	Where are the leaves?	Ina ganyayyakin?
2403065	What is on the man's eyes?	Mene a idanun mutumim?
2407844	What is the vehicle in the photo?	Wanne abun hawa ne a hoton?
2414305	What is behind the man in the photo?	Mene a bayan mutumin dake hoton?
2321163	Where was this photo taken?	A ina aka ɗauki wannan hoton ?
2321163	What is behind the women?	Mene a bayan matan?
2357597	What color is the water?	Mene launin ruwan?
2407969	How many windows are there?	Tagogin nawa ne a nan?
2332518	What color is the train?	Mene launin jirgin ƙasan?
2381564	How many window are directly above the entrance?	Taga nawa ne ce take saiti saman  wajan shigar?
2357217	What is the airplane's main color?	Mene ne ainihi launin jikin jirgin saman?
2385208	Where are the bottles?	Ina kwalaben?
2325217	How many horses are there?	Dokuna nawa ne a nan?
2387978	What color are the tower bricks?	Menene launin tubalin tower?
2410402	Who is holding the surfboard?	Wa ke riƙe da surfboard?
2410132	Where is the pathway?	Ina hanyar?
2374659	What is the person standing on?	Me mutumin yake tsaye a kai?
2343628	How many people can be seen?	Mutane nawa ake iya gani?
2343628	What is the wall made of?	Da me akayi bangon?
2380072	Why is the wine there?	Meyasa ruwan inibin yake nan?
2332812	Who is poking the fruit?	Wa yake bula kayan marmari?
2392157	What type of bus?	Wacce irin motar bas ce?
2319992	Who is in this picture?	Waye a cikin hoton?
2332812	What is on the man's face?	Mene a fuskar mutumin?
2374875	What is the kettle's handle made of?	Dame akayi mariƙin butar?
2366573	Where is the sheet?	Ina zanin gadon?
2319992	Where is the ball?	Ina kwallon?
2343628	Where are the glasses?	Ina madubin idon sa?
2393733	Where are the men and women?	Ina mazan da matan suke?
2408084	What color is the man's jersey?	Mene launin rigar mutumin.
2401685	Who is wearing the yellow coat?	Wake sanye rawayar riga?
2360541	What is the man doing?	Me mutumin yake yi?
2342718	What is behind the truck?	Menene a bayan babbar motar?
2408066	What year was this picture taken?	Wace shekara aka ɗauki wannan hoton?
2337917	What color are the cars?	Mene launin motoci?
2345905	When is the photograph taken?	A yaushe aka ɗauki hoton?
2334064	What color is the man's coat?	Mene launin rigar mutumin?
2335740	How many people are there?	Mutane nawa ne a nan?
2326735	What is the woman doing?	Me matar ke yi?
2404308	What is the name of the airline?	Ya sunan kamfanin jirgin saman?
2365424	What is sitting on bench?	Me ke zaune kan benci?
2366937	Where is the cake located?	A ina kek din yake?
2372533	Where was the photo taken?	Ina aka ɗauki hoton?
2348234	How many trains can be seen?	Jirgin ƙasa nawa ake gani?
2368296	What color is the disc holder?	Mene launin abun rike diski?
2385089	What color is the sky in this picture?	Mene launin sararin samaniya a hoton?
2396897	How many laptops are there?	Kwamfutar tafi da gidanka guda nawa ce a nan?
2316709	What is Under the bridge?	Mene a ƙasan gadar?
2341155	Why was the picture taken?	Meyasa aka ɗauki hoton?
2407844	Where is the aircraft?	Ina jirgin saman?
2332221	What is on the ground?	Mene a ƙasan?
2365173	Where are the people standing?	A ina mutanan ke tsaye?
2361427	What size of pizza?	Ya girman fizar?
2332518	Where is the train?	Ina jirgin ƙasan?
2357217	When was this taken?	A ina aka ɗauki wannan?
2367820	What kind of pants is the woman wearing?	Wanne irin wando matar tasa?
2362072	Where is the woman sitting?	Ina matar ke zaune?
2412909	What is in the basket?	Mene a kwandon M
2412909	Where are the bananas?	Ina ayabar?
2405608	How many signs are there?	Alamomi nawa ne a nan?
2378308	How many lights face each direction?	Fitulun nawa ne ke kallon juna?
2350133	Where is the water?	Ina ruwan?
2382489	How many dogs are in this picture?	Karnika nawa ne a hoton?
2376409	Where are the trees?	Ina bishiyun?
2376409	What are the green leaves on?	Ina koren ganye suke?
2376409	When was the picture taken?	A yaushe aka ɗauki hoton?
2360715	How many airplanes are in the picture?	Jiragen sama nawa ne a hoton?
2411204	What is the girl holding?	Me yarinyar ke riƙe dashi?
2406154	Where is the glove?	Ina safar hannun?
2366573	What is photo of?	Hoton meye wannan?
2353308	What time of day is it?	Wanne lokaci ne a rana ?
2393733	What is next to the food?	Mene ne kusa da abincin?
2330616	Who is standing in this picture?	Wake tsaye a wannan hoton?
2342718	When did the truck arrived?	Yaushe babbar motar ta zo?
2337917	What color is the woman's vest?	Mene launin rigar matar?
2392556	What is the man wearing?	Me mutumin ke sanye dashi?
2326735	How many elephants are there?	Giwayen nawa ne a nan?
2342336	How many cows are in the picture?	Shanu nawa ne a hoton?
2342336	What are the cows doing?	Me shagun suke yi?
2321088	When was the picture taken?	Yaushe aka ɗauka hoton?
2401712	What is in the left background?	Menene a hagun bayan?
2409343	How many sets of wheels is visible?	Ƙafafu nawa ake iya gani?
2366937	Where is the cake?	Ina kek ɗin?
2361917	What is the area around the doughnuts made of?	Da me akayi gurin da ya zagaye doughnuts ɗin?
2406164	When was the photo taken?	Yaushe aka ɗauki hoton?
2417947	What color is the person's jacket?	Wani launi ne da kwat ɗin mutumin?
2410341	What is in the blue bowl?	Menene a cikin shuɗin kwanon?
2335167	Where is the clock?	Ina agogon?
2389530	What is on the table?	Menene a kan tebur ɗin?
2393293	What kind of animal is in the photo?	Wacce irin dabba ce a cikin hoton?
2390965	Who is seen in the picture?	Wa ake gani a hoton?
2377847	What animal is shown?	Wacce dabba aka nuna?
2341155	Where was the picture taken?	A ina aka ɗauki hoton?
2341155	What is the picture showing?	Me hoton yake nunawa?
2405085	When was the picture taken?	A yaushe aka ɗauki hoton?
2399016	When was this picture taken?	Da yaushe aka ɗauki hoton?
2399016	What is the fruit resting on?	A kan me kayan itace yake ajiye?
2357597	Where was the photo taken?	A ina aka ɗauki hoton?
2316213	Where are the vegetables sitting?	A ina kayan lambun suke ajiye?
2341475	What color is his hat?	Mene launin hular sa?
2392531	What color is the train?	Mene launin jirgin ƙasan?
2392531	When was this picture taking?	Yaushe aka ɗauka hoton?
2323147	What color are the tree branches?	Wani launi ne da rassan bishiyar?
2381564	When was the photo taken?	Da yaushe aka ɗauki hoton?
2334649	Why is it bright outside?	Me yasa yayi haske a waje?
2382489	What color is the sky?	Mene launin sararin samaniya?
2339853	What is on the plate?	Mene akan farantin?
2363898	What color is the sky?	Wani launi ne da sama?
2409318	What number is on the headlight?	Wacce lamba ce a jikin fitilar babur din?
2407228	What color is the boat on shore?	Wani launi da jirgin ruwan dake bakin ruwan?
2360978	What does the big black sign say?	Me babbar baƙar alamar ta ce?
2368217	Where does the scene take place?	A ina hakan ya faru?
2365859	What color are the elephants?	Mene ne launin giwayen?
2410402	What is in the water?	Mene a cikin ruwa?
2340549	What is the sport?	Wanne wasa ne?
2343628	How many cell phones are shown?	Wayar salula guda nawa aka nuna?
2353308	How many No Entry signs are visible?	Alamar baa shiga guda nawa ake gani?
2386985	Where is the bus parked?	A ina aka ajjiye motar bas din?
2372365	What color is the man's sweater?	Mene launin rigar sanyin mutumin?
2386985	Where was this photo taken?	A ina aka ɗauki wannan hoton?
2417707	How many people are visible?	Mutane nawa ake iya gani?
2345905	Where are the people?	Ina mutanen?
2349179	When was the photo taken?	Da yaushe aka ɗauki hoton?
2409343	What color is the runway?	Mene launin titin jirgin saman?
2373171	What color is the cloth on the small table?	Mene launin kayan dake kan karamin tebur?
2348234	What can be seen on the far left?	Me ake iya gani a can gefen hagu?
2360550	Where are the awnings?	Ina rumfar?
2377160	What are the ducks doing?	Me agwagi suke yi?
2405644	What color is the water?	Mene ne launin ruwan?
2345475	Where was the photo taken?	A ina aka ɗauki hoton?
2346896	When was the picture taken?	Yaushe aka ɗauki hoton?
2394499	What is the position of the dog's ears?	Yaya matsayin kunnen karen?
2402676	Why is she playing?	Meyasa take wasan?
2384900	What is on television?	Mene a ka saka talabijin?
2321163	Why are are their feet not visible?	Meyasa baa ganin tafin kafarsu?
2407334	How many giraffes are there?	Raƙumin dawa nawa ne a nan
2373259	What is the kid with red on doing?	Me yaron da ke sanye da jan yake?
2360918	What is on the bus?	Mene ne a jikin maitar bas din?
2360918	What kind of vehicle?	Wacce irin abun hawa?
2323147	Where are the leaves?	Ina ganyayyakin suke?
2334649	How many giraffes are shown?	Raƙumin dawa nawa aka nuna?
2412909	How does the basket not fall?	Taya kwandon bai fadi ba?
2342608	Who are in the photo?	Suwaye a hoton?
2370667	What type of animal?	Wanne irin dabbobi ne?
2413449	What color is the chair?	Mene launin kujerar?
2333612	What color pepper is on the pizza?	Wanne launin attaruhu ne a kan fiza?
2365859	Where are the elephants?	Ina giwayen?
2322820	What is the person in white doing?	Me mutumin dake sanye da farar yake yi?
2371578	What color are the cow's legs?	Mene launin kafar sa?
2410132	How many horses are in the picture?	Dokuna nawa ne a hoton?
2342718	What is the color of the truck?	Mene launin babbar motar?
2417707	What is on the person's head?	Mene ne a kan mutumin?
2335297	What color is the child's shirt?	Mene launin rigar yaron?
2371973	What is the sign color?	Mene launin allon alama.
2408066	What is open?	Mene a bude?
2408066	Who is in the suitcase?	Waye a cikin akwati?
2334064	What color is the snow?	Mene launin dusar ƙanƙara?
2381488	Where is this picture taken?	A ina aka ɗauki wannan hoton?
2366911	How many traffic lights are there?	Fitular zirga-zirga nawa ce a nan?
2360697	What is that on the plate?	Mene a kan faranti?
2342336	How many white cows are there?	Fararan shanu nawa ne?
2342336	Where was this picture taken?	Ina aka ɗauki wannan hoton?
2321088	Why are the leaves falling?	Meyasa ganyen suke faduwa?
2321088	What color are the leaves?	Mene launin gayan?
2401712	What is the main color of the eyes?	Mene ainihin launin idanun sa .
2366011	What color are the trees?	Mene launin bishiyun?
2366011	What kind of animal is there?	Wanne irin dabba ce a nan?
2328205	What is the color of the zebras?	Mene ne launin jakin dawa?
2393112	How do the cars know when to stop?	Yaya motoci suke sani lokacin tsayawa?
2328845	Where are the white chairs?	Ina fararan kugerun?
2373710	What is black in color?	Mene mai launin baƙi.
2385089	Where was this picture likely taken?	A ina ake tunanin an ɗauki hoton nan?
2335167	What is this?	Mene wannan?
2414610	When was this photo taken?	A yaushe a ka ɗauki wannan hoton?
2414610	What is the color of the skirt?	Mene ne launin sikket din?
2389530	What is about to happen to the pizza?	Meke shirin faruwa ga fiza?
2389530	What is the plate's color?	Mene launin jikin faranti?
2389530	How many lime slices on the table?	Yankakken lemon tsami nawa ne a kan tebur?
2414579	What is on top of the box?	Mene a saman kwalin?
2394763	What is the guy holding?	Me mutumin ke riƙe dashi.
2317967	Who is riding the motorcycle?	Waye mai tuƙa babur din?
2346896	What are the people walking on?	A ina mutane suke tafiya?
2342468	What is behind the person?	Mene a bayan mutumin?
2384900	Where is the television?	Ina talabijin
2378502	What color is the sheep's head?	Mene launin kan tukiyar?
2405531	What color is the ground?	Mene launin ƙasan?
2361427	Where is the pizza?	Ina fiza take?
2360918	What color is the bus?	Wanne launin ne jikin motar bas din
2360089	What is coming through the window?	Me ke shigowa ta taga?
2405608	What is on the lower left of the photo?	Mene a ƙasan hadun hoton?
2347694	Who is under the train?	Wane a ƙasan jirgin ƙasa?
2347694	How may people are there?	Mutane nawa a nan?
2407228	What is on the river water?	Mene a cikin ruwan kogin?
2317456	When was the photo taken?	A yaushe aka ɗauki hoton?
2347287	What color is the banana?	Mene launin ayabar?
2391575	Who is walking down the sidewalk?	Waye ke tafiya a gefen hanya?
2366157	What color helmet is the person wearing?	Wanne launin hular kwanon mutumin ke sanye dashi?
2376409	What type of plant is surrounding the road?	Wacce in shuka ce ke zagaye da titin?
2370651	When was the game played?	A yaushe akayi wasan?
2392556	Where is the man?	Ina mutumin?
2326735	What is the elephant doing?	Me giwar take yi?
2326735	When was the pic taken?	Da yaushe aka ɗauki hoton?
2390724	Why are the oranges sliced?	Me yasa aka yanka lemon zakin?
2404308	What are the planes going to carry?	Me jirgin saman zai dauka?
2330938	How many people are there?	Mutane nawa ne a nan?
2323235	How is the girl passing her time?	Yaya yarinyar take cin lokacin ta?
2323235	How is the girl traveling?	Ya yarinyar ke tafiyar?
2401712	What is on top of the giraffe's head?	Mene a saman kan raƙumin dawan?
2366011	What is the sky?	Mene a sararin samaniya?
2393112	Where are the electric wires?	Ina wayoyin wutar lantarki
2393819	Who is wearing a white shirt?	Waye ke sanye da farar riga?
2390965	How is the girl going to eat the sandwich?	Ta yaya yarinyar zata ci sandwic din?
2412517	What color is the table?	Mene launin tebur din?
2405531	How many people are pictured?	Mutane nawa ne a hoton?
2357597	How many people can be seen?	Mutane nawa ake iya gani?
2316213	What color are the tomatoes?	Mene launin tumatur din?
2338525	What is he doing?	Me yake yi.
2315483	What color are the trees?	Mene launin bishiyun?
2381564	What color is the building?	Mene launin gini?
2360089	What is the brown wooden object?	Mene na katako kuma ruwan ƙasa?
2357217	How many airplanes are there?	Jirgin sama nawa ne a nan
2362072	What is under the bench?	Mene a ƙasan bencin?
2402563	How many clocks are pictured?	Agogo nawa ne a hoton?
2342608	What color is the sky?	Mene launin sararin samaniya?
2378308	How many directions is the traffic light?	Ɓangaren nawa ne hasken zirga-zirga ya kasu?
2317456	How many people are in the photo?	Mutane nawa ne a hoton ?
2364367	What is the woman holding?	Me matar ke riƙe dashi?
2371578	What does the woman in front have on the feet?	Me matar dake gaba take dashi a ƙafar ta?
2363672	What is green color?	Mene mai launin kore?
2374396	What side is the green train on?	Ta wanne ɓangaren jirgin ƙasan yake?
2364899	How many people are there?	Mutane nawa ne a nan?
