2380072	Who is in the pic?	Waye a hoton?
2408925	Where is the cat standing?	A ina magen ke tsaye?
2332812	What color is the fruit?	Mene launin abun marmari?
2386985	When was this photo taken?	A yaushe aka ɗauki wannan hoton?
2386985	What color is the grass?	Mene launin ciyawar?
2377924	What item is used to hear?	Wanne abu ake anfani dashi wajan ji?
2334064	What color is the sign?	Mene launin alama ?
2417901	How many children wearing hats?	Yara nawa ke sanye da hula?
2333844	Who is standing on the tracks?	Wake tsaye a hanyar jirgin ƙasan?
2406916	Where is window?	Ina tagar?
2403741	Where are the zebras?	Ina dakunan dawa?
2372034	What is on the table?	Mene akan tebur din?
2372034	How much pizza remains on the table?	Fiza nawa ce tayi ragowa a kan tebur?
2323235	Where is the girl in the picture?	Ina yarinyar a hoton?
2401712	What's the number of giraffes in the picture?	Raƙumin dawa nawa ne a hoton?
2372104	What is orange and black?	Mene mai ruwan goro kuma baƙi?
2335167	What is it made of?	Dame akayi shi?
2394763	Where is the mirror?	Ina madubin?
2405085	Who is riding the horse?	Waye ya hau doki?
2398981	Why is the person in the air?	Meyasa mutumin yake cikin iska?
2332221	Where is this scene?	Ina ne hakan?
2332221	Why is it bright?	Meyasa yayi haske?
2390299	What is this food?	Wanne abinci ne?
2373259	How many bald adults are there?	Maza nawa ne marassa gashi a wajan?
2360918	What amount of colors on bus?	Launika nawa ne a jikin motar bas din?
2315483	When was the picture taken?	Da yaushe aka ɗauki hoton?
2351388	Where was the photo taken?	A ina aka ɗauki hoton?
2325181	What plant is partially visible?	Wacce shuka ce ake ɗan ganin ta?
2325217	Who has a tail?	Waye yake da jela?
2382489	What color is the grass?	Mene launin ciyawar?
2407228	What color is the writing on the boat?	Mene launin rubuta jikin kwalekwale?
2333612	What color are the plates?	Mene launin farantan?
2363917	What number is in the circle?	Wacce lamba ce aka zagaye?
2366157	Where is the water?	Ina ruwan yake?
2368217	Where are many small windows?	A ina ƙananun taga suke masu yawa?
2346599	What color are the flowers?	Mene launin furanni ?
2342457	Where is this scene taking place?	A ina haka ne faruwa?
2366573	Where is the face?	Ina fuskar?
2330616	What time of day is it?	Wanne lokaci ce wannan?
2358256	What type of bird is this?	Wanne irin tsuntsu ne?
2377924	What item has a metal handle?	Wanne irin abun ne mai hannun ƙarfe?
2334064	What color are the man's pants?	Mene launin jirgin wandon mutumin?
2333844	What color are the train's stripes?	Mene launin layin dake jikin jirgin ƙasan?
2403741	Where are the zebras?	Ina jakunan dawa?
2355345	What color are the shirts of the men?	Wanne launin riga ce a jikin mazen?
2406991	How many men are there?	Maza nawa ne a nan?
2365424	What is the bench made of?	Dame akayi bencin?
2323235	Where is the wrist watch?	Ina agogon hannun?
2393112	Where is the clock tower?	Ina agogon hasumiya?
2328845	What color is the ball?	Mene launin kwallon?
2328845	What color are the wheels?	Mene launin ƙafafu?
2377160	What type of birds are the smaller birds?	Wacce irin tsuntsu ne ƙanana.
2394499	Where is the dog?	Ina karen?
2394499	What is the dog on?	Akan me karen yake?
2412517	What color is the table?	Mene launin tebur din?
2412517	What is behind the food?	Mene a bayan abincin.
2332221	How many umbrellas?	Lema nawa ne?
2332221	What is in the background?	Mene a ƙasan bayan hoton?
2405531	What color is the elephant?	Mene launin giwar?
2361427	Where is the pizza?	Ina fiza din?
2316213	What does the sign say?	Me ake ce a jikin alamar?
2373259	How many blue bibs are visible?	Shuɗin bib nawa ake iya gani?
2341475	Who is on the bike?	Waye kan keke?
2338525	What is in the background?	Mene ne a ƙasan bayan hoton?
2315483	What color are the rocks?	Mene launin dutsen?
2324028	Who are the people in the picture?	Suwa mutanan dake jikin hoton?
2365859	What are elephants doing?	Me giwar take yi?
2364367	Where is this photo taken?	A ina aka ɗauki wannan hoton?
2387978	Where is the tree?	Ina bishiya?
2408925	Why is the cat eating?	Meyasa mage ke cin abinci?
2322820	What color is the cow?	Menene launin jikin San.
2409878	Who is wearing gloves?	Waye yake sanye da safar hannun?
2410402	What is in the water?	Mene a cikin ruwan?
2411204	Who is wearing red?	Wake sanye da jar riga?
2410132	Where is the fence?	Ina dangar?
2406154	What color is the grass?	Mene launin ciyawar?
2408925	Where is cat food?	Ina abinci mage?
2408084	What is the man doing?	Me mutumin ke yi?
2392157	What is in the front window of the bus?	Mene ne a gaban tagar motar bas din?
2374875	Where is the teapot positioned?	Ina tukunyar shayin take?
2343628	What color is the cellphone?	Mene launin jikin wayar salula?
2353308	Where are the Dali banners displayed?	A ina aka sanya tutocin Dali?
2346613	What kind of animal is in the picture?	Wanne irin dabba ce a hoton?
2391897	Where is the round white decoration?	Ina farin zagayayye abin adon?
2374875	What appliance is this?	Wanne kayan amfani ne wannan?
2318313	What color is the building?	Mene launin gini?
2415614	What is on the woman's hip?	Mene a kugun matar?
2338734	What colors are the cows?	Mene launin jikin shanu?
2386251	When is this taken?	Yaushe aka ɗauki wannan?
2326516	When is this taken?	Yaushe aka ɗauki wannan?
2326516	What type of animals are pictured?	Wanne irin dabbobi aka ɗauka hoton?
2321264	When was this photo taken?	A yaushe aka ɗauki wannan hoton د
2365326	What kind of picture is on the right?	Wanne irin hoton ne a dama?
2376147	What are the small red balls?	Mene ne ƙananu kuma jajayen kwallo?
2401318	What is the main color of the letter C?	Mene ainihin launin harafun C?
2378419	What color is the bike's tire?	Mene launin tayar babur din?
2332102	When was picture taken?	Yaushe aka ɗauki hoton?
2352633	What time does the clock say?	Ƙarfe nawa agogon yace?
2375565	What is hanging in front of the bike?	Mene rataye a gaban babur din?
2384078	What two colors are on the flag painted on the train?	Waɗanne launika ne guda biyu a jikin tutar da akayi fentin ta jikin jirgin ƙasan.
2356158	Where is the fork?	Ina cokalin yatsu yake?
2368690	Who is sitting in a chair?	Waye ke zaune a kujera?
2381594	What color is the side of the train?	Mene launin gefen jirgin ƙasan?
2404093	What is the main color of the leaves?	Mene ainihin launin ganyayyakin?
2349854	What are the foods on?	Me abincin yake kai?
2326386	When was this picture taken?	Yaushe aka ɗauki wannan hoton m
2415472	Where is person with white shirt?	Ina mutumin dake sanye da farar riga?
2398174	What color is the street?	Mene launin titin?
2403452	How many planes do you see?	Jirgin sama nawa aka gani?
2376147	When is the picture taken?	Yaushe aka ɗauki hoton?
2412490	What is painted green?	Mene mai fenti kore?
2339629	What are the sheep eating?	Me tumaki ke ci?
2393344	What animals are in the picture?	Wanne dabbobi ne a hoton?
2375565	What is orange on the bike?	Mene mai launin ruwan goro a babur din?
2394870	What is present?	Mene a nan?
2387890	Where is this picture taken?	A ina aka ɗauki wannan hoton?
2363837	How many of the people are women?	Mata nawa a cikin mutanen?
2379989	When was this photo taken?	Yaushe aka ɗauki wannan hoton?
2364025	Where are the boy's hands?	A ina hannayen yaron suke?
2338734	Where are the cows?	Ina shanu?
2338734	Who is in the picture?	Waye a hoton?
2338734	How many cows can be seen?	Shanu nawa ake iya gani?
2334735	What color are the majority of the boats?	Wanne launin mafi yawan jirgin ruwa suke dashi?
2398038	What are the boats floating in?	Jirgin ruwan suna yawo a Ina?
2403260	Where are the sheep?	Ina tunkiyoyi suke?
2410331	What is the color of the wall?	Mene launin bangon?
2350144	When was the photo taken?	Yaushe aka ɗauki hoton?
2393406	What is near the umbrella?	Mene kusa da lema?
2376147	Who is eating?	Wake cin abinci?
2323919	How many blue and white players are shown?	Yan wasa masu shuɗi da fari nawa aka nuna?
2378419	Who is in the photo?	Waye a hoton?
2411258	What's the color of the table?	Mene launin tebur din?
2338152	What animals are in the picture?	Wacce dabbobi ne a hoton?
2412490	Who are riding on the buses?	Suwaye suka hau motoci bas?
2385611	Where is the cat lying?	Ina magen ke kwance ?
2356292	Who is behind the table?	Waye a bayan tebur din?
2341544	How is the weather?	Ya yanayi garin ?
2383236	What color is the paper?	Mene launin jikin takardar?
2406459	How many motorcycles are there?	Babur nawa ne a nan?
2370761	What is lighting up the scene?	Me ya haskaka yanayi?
2354294	Why is the man wearing glasses?	Meyasa mutumin ya saka madubi idanu?
2359857	Where is the window?	A ina tagar take.
2346613	How many dogs are in the picture?	Karnika nawa ne a hoton?
2372504	Where are the trees?	Ina bishiyun suke?
2332663	What color are the boys shorts?	Mene launin wandon yaron?
2398174	When was the photo taken?	Yaushe aka ɗauki hoton?
2398038	What is seen in the distance?	Me ake gani a can nisa?
2319425	What color is the sky?	Mene launin sararin samaniya?
2339629	Where is the fence?	Ina dangar?
2375565	What is all over the tire?	Mene a jikin taya?
2384078	How many train windows are pictured?	Tagogin jirgin ƙasa nawa ne a hoton?
2383236	What color is the cat?	Mene launin jikin magen?
2331263	When was this photo taken?	Da yaushe aka ɗauki wannan hoton
2374316	Why is she smiling?	Meyasa take murmushi?
2379989	What color is the girl's shirt?	Mene launin rigar yarinyar?
2345970	When was this photo taken?	Yaushe aka ɗauki wannan hoton?
2345970	Who is in the sky?	Waye a sararin samaniya?
2317662	What color is the arrow sign?	Mene launin alamar kibiyar?
2338734	When is the picture taken?	Da yaushe aka ɗauki hoton?
2327770	What color is the ground?	Mene launin ƙasan?
2386251	What color is the bicycle?	Mene launin jikin keken?
2374744	What type of computer is this?	Wanne irin na'ura komfuta ce wannan?
2403260	Where are the trees?	Ina bishiyun?
2350144	Where is the man?	Ina mutumin?
2345063	How many cats are in the picture?	Maguna nawa ne a hoton?
2411258	What's the color of the plate?	Mene launin farantin?
2401569	What color are the trees?	Mene launin bishiyun?
2338152	How many animals are in the picture?	Dabbobi nawa ne a hoton?
2412490	What color is the line next to the green bus?	Mene ne launi layin dake kusa da Koriya bas.
2385611	What direction is the cat looking?	Wanne ɓangaren magen ke kalla?
2363939	Where is the pillow?	Ina matashin kai yake?
2341544	What are the people doing?	Me mutane suke yi?
2394870	Who is in the picture?	Waye a hoton?
2377909	How many people can be seen in this picture?	Mutane nawa ake iya gani a wannanh oton?
2346276	What time of day is it?	Wanne lokaci wannan?
2374316	What is on the feet of the baby?	Mene ne a ƙafar jaririn?
2364025	What is white on the grass?	Mene fari a kan ciyawar
2318339	What color is the sky?	Mene launin sararin samaniya?
2350144	What is on the ground?	Mene a ƙasa?
2350144	Why is the man in the street?	Meyasa mutumin ke kan titi?
2401318	Where is a window?	Ina tagar take?
2372168	Who has blue eyes?	Waye ke da shuɗi ido?
2341119	What kind of room is this?	Wanne irin  daki ne wannan?
2401569	Where are the trees?	Ina bishiyun?
2319425	How many motorcycles are there?	Babur nawa ne a nan?
2362135	What is in the cup?	Mene a moɗar?
2364752	Where are the cut vegetables sitting?	Ina yankakkun kayan lambu suke?
2339629	When was this picture taken?	Yaushe aka ɗauki wannan hoton?
2392672	Where are the birds?	Ina tsuntsaye?
2381594	How many train tracks are there?	Hanyar jirgin ƙasa nawa ne a nan?
2326386	What color is the water?	Mene launin ruwan?
2364025	Where are the white flowers?	Ina fari furanni?
2330319	What color are the bedsheets?	Mene launin zanin gadon?
2376291	Who is visible in this picture?	Wa ake gani a cikin hoton?
2398038	What can be seen in the distance?	Me ake gani a nesa?
2367932	Where is the spire on the church?	Ina spire yake a coci?
2403452	When was picture taken?	Yaushe aka ɗauki hoton?
2336048	What color is the table the gray laptop is on?	Menene launin teburin da kwanftar tafi da gidan ka ruwan kasa take kai?
2410331	What color is the ramp?	Menene launin ramp?
2371319	What is in the grass?	Menene a cikin ciyawa?
2371319	What way are the elephants facing?	Wani ɓangare giwayen suke kallo?
2376147	What is the white clumps?	Menene fari curarre?
2323919	What color is the dirt?	Menene launin ƙasar?
2341119	What color is the towel on the balcony?	Menene launin tawul din da ke balcony?
2401317	When will the car near the crosswalk be gone?	Yaushe motar da ke kusa wurin tafiya zata tafi?
2366107	What is painted green?	Meye fenti kure?
2384078	What color is the sky in the photo?	Meye launin sararin samaniya a hoton?
2380626	What is the horse doing?	Me dokin yakeyi?
2380626	What is the white animal?	Meye farin dabbar?
2381594	How many headlights does the train have?	Fitila nawa ce a jirgin kasan?
2354294	Where Are the man's glasses?	Ina gilashin mutumin?
2346276	What is the man doing?	Me mutumin keyi?
2346276	What color is the water?	Me launi ruwan?
2379989	How many people do you see?	Mutane nawa ka gani?
2346613	Where is the picture taken?	A ina aka dauki hoton?
2330319	How many women are on the bed?	Mutane nawa ne akan gadon?
2334735	How many birds are shown in the photo?	Tsuntsu nawa ne ya nuna a hoton?
2339362	Where was this picture taken?	A ina ka dauki hoton?
2410331	What age is the boy?	Meye shekarun yaron?
2401318	How many airplanes are there?	Jirgi nawa ne a gurin?
2372168	What is the boy doing?	Me yaron ya keyi?
2378419	Why is the picture clear?	Meyasa hoton yay tar?
2380626	How many horses are in the picture?	Doki nawane a hoton?
2368690	What game is being played?	Wani wasa akeyi?
2393936	What is the wall's color?	Meye launin bangwan?
2387890	Where is the grass?	Ina ciyawar take?
2387890	Where is the concrete?	Ina kankare?
2363837	Who is in the water?	Waye acikin ruwan?
2415472	What are they watching?	Me suke kallo?
2368442	Where is the ball?	Ina kwallon?
2318313	What color is the ground?	Mene launin ƙasan?
2346613	How many people are on the beach?	Mutane nawane a bakin ruwan?
2391897	How many clocks?	Agogo nawane?
2332663	What color is the man's sandals?	Meye launin sandal din mutumin?
2410331	How many people are in the photo?	Mutane nawa ne a hoton?
2365326	What is the boy holding?	Me yaron yake riƙe dashi?
2376147	What is the bright light?	Meye me hasken?
2372168	What is the hand holding?	Me yake riƙe dashi a hannu?
2316371	What color is the sky?	Me launin sararin samaniya?
2401569	What is green in the image?	Meye kore a hoton?
2341544	What color is the sky?	Mene launin sararin samaniya?
2392672	Who is next to the birds?	Waye a kusa da tsuntsayen?
2387890	What color is the jacket?	Meye launin rigar?
2377909	What is green things placed on pizza?	Meye koren abun da yake kam pizza din?
2346276	Who is surfing?	Wa yake hawa kan igiyar ruwa?
2331263	Where are the animals looking?	Ina dabbobin suke kalla?
2384725	What color is the table mat?	Meye launin tabarmar kan tebur?
2318313	Where is the building?	Ina ginin yake?
2391897	What shape is the clock?	Meye siffar agogon?
2391897	Where are the buildings?	Ina gina ginan suke?
2386251	How many people are on the bicycle?	Mutane nawa ne a kan keke?
2374744	What is the desk made out of?	Dame akayi tebur din?
2360695	Where are the lights?	Ina fitular suke?
2401317	What is the fence on the right made of?	Dame akayi dangar dame gefen damar?
2356292	Where are the bananas?	Ina ayabar
2356292	When was this taken?	Yaushe aka ɗauki wannan?
2339629	Where was this photo taken?	A ina aka ɗauki wannan hoton?
2393344	What is in the photo?	Mene ne a hoton
2375565	Where is the motorcycle parked?	A ina aka ajjiye babur din?
2356158	What are they drinking?	Me suke sha?
2394870	When was this?	Yaushe hakan?
2403452	What is white?	Mene ne fari?
2341119	What color are the bed sheets?	Mene launin zanin gadon?
2319358	How many people are in this photo?	Mutane nawa ne a wannan hoton?
2319358	What color are the flowers in the window?	Mene launin furanni dake taga?
2363939	Where is the cat sleeping?	Ina magen ke barci?
2383236	What is the cat sitting on?	Akan me magen ke zaune?
2354294	What Color is the man's shirt?	Mene launin rigar mutumin?
2345970	What color is the water?	Mene launin ruwan?
2331263	What are pictured in this photo?	Hoton mene wannan?
2317662	Where is the stop sign?	Ina alamar tsayawa?
2363080	Where is the girl?	Ina yarinyar take?
2332663	What color is the cup that the little boy is holding?	Mene launin moɗa da karamin yaron ke riƙe dashi.
2327770	How many people are skiing?	Mutane nawa ke wasan gudun ƙanƙara
2386251	What does the sign in the background say?	Me alamar dake ƙasan bayan yace.
2346613	What color is the dog?	Mene launin jikin karen?
2393406	What is next to the umbrella?	Mene kusa da lema?
2378419	When was the photo taken?	Yaushe aka ɗauki wannan hoton?
2412490	What color is the front bus?	Mene launin motar bas din?
2385611	What color are the cat's eyes?	Mene launin idon magen?
2380626	Who is in the picture?	Waye a hoton?
2398813	What is the sidewalk made of?	Dame aka yi gefen hanyar?
2349854	Where is the fruit placed?	A ina aka ajjiye kayan marmari?
2346276	How many people in the photo?	Mutane nawa ne a hoton?
2415472	Who is watching TV?	Wake kallon TV?
2368442	Where is the tennis ball?	Ina kwallon tanis?
2363080	What color is girl's shirt?	Mene launin gashin yarinyar?
2359857	What animal is attached to the cart?	Wacce dabba aka ɗaura wa amalanke?
2364025	What is white in color?	Mene mai launin fari?
2344252	How many toilets are there?	Masai nawa ne a nan?
2384725	When was this photo taken?	A yaushe aka ɗauki wannan hoton?
2364049	What is beside the bus?	Mene a kusa da bas din?
2364049	What is the bus doing?	Me motar bas din ke yi?
2398174	What color os the bus nearest the camera?	Mene launin motar bas din dake kusa da kamera?
2326516	What color are the elephants?	Mene launin jikin giwayen?
2376291	When was this picture taken?	Da yaushe aka ɗauki wannan hoton?
2341119	What color cup is on the table?	Mene launin moɗar dake kan tebur?
2364752	What is behind the table?	Mene a bayan tebur din?
2380626	What direction is the horse facing?	Wanne gefe dokin ke fuskanta?
2392672	Where are the white feathers on the birds?	Ina fararen gashi yake a jikin tsuntsaye?
2392672	What covers the animals?	Me ya rufe jikin dabbobin?
2405201	What kind of chairs are in the middle of the picture?	Wacce irin kujeru ne a tsakiyar hoton?
2370761	Where is the bench?	Ina benci yake?
2349854	What color is the table?	Mene launin tebur din?
2379989	What is pulling the little girl?	Meke jan ƙaramar yarinyar?
2344252	What color is the toilet?	Mene launin matsuguni?
2344252	What is around the child's neck?	Meke rataye a wuyan yarinyar?
2407162	What color is the no left turn sign?	Mene launin alamar kar a juya hagu?
2318313	What is hanging in the background?	Meke rataye a bayan ƙasan hoton?
2384725	What color is the plate?	Mene launin farantin?
2339362	How many bottles are in the picture?	Kwalabe nawa ne a hoton?
2318339	When was this taken?	Yaushe aka ɗauki wannan?
2410331	What is in the background?	Mene a bayan ƙasan?
2393406	What is the fence connected to?	Dangar ba haɗi da me?
2365326	When was this photo taken?	Da yaushe aka ɗauki wannan hoton?
2341119	When was this photo taken?	Da yaushe aka ɗauki wannan hoton?
2393344	Where are the elephants?	Ina giwayen?
2319358	What two colors are the words?	Waɗanne launika ne jikin kalmar?
2352633	What is on the tower?	Mene jikin hasumiya?
2352633	Where is the clock?	Ina agogon?
2356158	Where is the knife?	Ina wuƙar?
2406459	What color is the bus?	Mene launin bas?
2406459	Where is the lady?	Ina matar?
2398813	Where was this picture taken?	A ina aka ɗauki wannan hoton?
2359857	Who is sitting in the cart?	Suwaye suke zaune a amalanke?
2403260	What keeps the sheep in?	Me ya ajjiye tumaki waje ɗaya?
2385611	When was the picture taken?	Yaushe aka ɗauki hoton nan?
2332102	What is beside cat's head?	Mene kusa da kan magen?
2406459	What is the lady on?	Me matar take kai?
2398813	Where are the shadows?	Ina inuwar?
2370761	Where is the row of trees?	Ina jerin layin bishiyun?
2331263	Where are these animals?	Ina waƴennan dabbobin?
2415472	What co!or is lampshade?	Menene launin futular?
2374316	What is the baby holding?	Me jaririyar take riƙe da?
2374316	Who is holding the paper?	Wa ke riƙe da takardar?
2379989	What is behind the horse?	Menene a bayan dokin?
2335079	How many colors are in the toothbrush handle?	Launika nawa ne a jikin hannun toothbrush?
2374875	What is this room?	Wani ɗaki ne nan?
2407162	Where are the ramps?	Ina ramps suke?
2415614	What is the man and woman doing?	Me mace da namijin suke yi?
2415614	Who is in the photo?	Waye a cikin wannan hoton?
2332663	What is the man holding?	Me mutumin yake riƙe da?
2332663	Where is the Wii console?	Ina wii console yake?
2326516	What is the sky like?	Yaya sama take?
2398038	What is to the right of the water?	Menene a gefen damar ruwan?
2323919	What color is the base?	Menene launin base?
2345063	What color is the window trim?	Menene launin datsar tagar?
2411258	What is in the green bottle to the upper left?	Menene koren kwalba daga hagu sama?
2401317	What kind of structure is in the middle distance?	Wani irin tsari ne a tsakiya a nesa?
2338152	Why are their eyes closed?	Meyasa idanun su suke a rufa?
2364752	What is sitting in the wooden block?	Me ke a kan katakon?
2356292	How many people are there?	Mutane nawa ne a wurin?
2366107	Who is wearing the red jacket?	Wa ke sanye da jar jacket?
2393344	How many elephants are facing the camera?	Giwaye nawa ke kallon kamera?
2363939	What are the cats doing?	Me maguna ke yi?
2393936	Where is the man's hand?	Ina hannun mutumin?
2363837	How many people are in the water?	Mutane nawa ne a ruwan
2405201	How big is the room where the picture was taken?	Ya girma ɗakin da aka ɗauki wannan hoton a ciki.
2354294	How many men are there?	Maza nawa ne a hoton?
2367360	What color are the sheep?	Mene launin tunkiya?
2338114	What are between the fence and the buildings?	Mene tsakanin dungar da ginin?
2363014	Who has black hair?	Yaye ke da baƙin gashi?
2376332	What animal is displayed?	Wacce dabba aka nuna?
2376332	Who is in the picture?	Waye a hoton?
2336041	When did the plane take off?	Yaushe jirgin ya tashi?
2374977	What number of pizzas?	Fiza nawa ce?
2402657	What color is the dog's nose?	Mene launin hancin kare?
2340279	How many people are showing in the image?	Mutane nawa suka fito a hoton?
2345589	What color are the bananas?	Mene launin ayabar?
2336292	How many people are there?	Mutane nawa a nan?
2385255	When was the pic teken?	Yaushe aka ɗauki hoton?
2410531	What color are the man's shorts?	Mene ne launin wandon mutane?
2341416	When was this photo taken?	Yaushe aka ɗauki wannan hoton?
2354144	How many buses are on the street?	Motar bas nawa ce a titi?
2411351	What is over the man's head?	Mene akan mutumin?
2351039	How many people are in the image?	Mutane nawa ne a hoton?
2414214	What shape are the fruits?	Wacce siffar ce da kayan marmarin?
2392528	What is the woman wearing on the head?	Me matar ke sanye dashi a kanta?
2408813	Where are the two benches?	Ina benci guda biyu suke?
2387827	What color is wall behind the bananas?	Mene launin bangon dake bayan ayabar?
2335754	When was this picture taken?	Da yaushe aka ɗauki wannan hoton?
2336292	When was the photo taken?	A yaushe aka ɗauki hoton ?
2359580	What is the number displayed on the bus?	Wacce lamba ke nuni a jikin bas din?
2410531	What color is shirt?	Menene launin rigar sa?
2343297	When was this photo taken?	Yaushe aka ɗauki wannan hoton?
2415964	Where is this scene?	Ina ne nan?
2344495	What color is the grass?	Mene launin ciyawar?
2388959	What animal is shown?	Wacce dabba ce ta fito?
2408406	What color is the tip of the umbrella?	Mene launin saman karshen lemar?
2363154	What is building made of?	Dame akayi ginin?
2363154	How many floors is the left building?	Hawa nawa ne a gefen hagun ginin?
2392528	What is brown in the photo?	Mene mai launin ruwan ƙasa a hoton?
2396341	What is the yellow food on the table?	Wanne abinci ne mai launin rawaya a kan tebur din?
2416681	How many baskets are there?	Kwando nawa ne a nan?
2390523	What material is the counter made of?	Dame aka yi kantar?
2402829	When was this taken?	Yaushe aka ɗauki wannan?
2401945	What is the ball's color?	Mene launin kwallon ?
2318638	How many people are shown?	Mutane nawa ne suka fito?
2316928	What is on the man's head?	Mene akan mutumin?
2359279	What is next to the toilet?	Mene kusa da masai?
2361344	How is the image taken?	Taya aka ɗauki hoton?
2362259	What does the man have?	Me mutumin ke dashi?
2410531	What is the man wearing as pants?	Me mutumin ke sanye dashi a matsayin wando?
2365624	What has white stomachs?	Meye mai launin jiki fari?
2411997	When was this picture taken?	Yaushe aka ɗauki wannan hoton?
2411997	What is the man doing?	Me mutumin ke yi?
2411997	How many motorbikes are in the scene?	Babur nawa ne nan?
2328298	What color is the fence?	Mene launin dungar?
2373285	What is black color?	Mene baƙi
2351039	Where is this taken?	A ina aka ɗauki wannan?
2374734	What color is the building?	Mene launin ginin?
2402829	What are the zebras doing in the water?	Me jakin dawa yake yi a ruwa?
2402829	What color is the grass?	Mene launin ciyawar?
2395872	What condition is the road in?	Ya yanayi titin yake?
2318638	When was the photo taken?	Yaushe aka ɗauki hoton?
2379559	How many cats are pictured?	Maguna nawa aka nuna?
2412914	What color is the scissors?	Menene launin almakashin?
2353318	How many women are there?	Mata nawa ne a wurin?
2360930	What is on the ground?	Menene a ƙasa?
2372344	Where is the man skateboarding?	Ina mutumin yake skateboarding?
2410531	What is court made of?	Da me akayi filin?
2370181	Where is this meal taking place?	Ina cin abincin na  ke faruwa?
2346879	Where is the Eiffel Tower?	Ina Eiffel Tower?
2413695	Where are the animals?	Ina dabbobin suke?
2413695	What is in the background?	Menene a baya?
150324	How many men are standing?	Maza nawa ne a tsaye?
2361225	What color is the man's hat?	Menene launin hular mutumin?
2397109	What color is the canopy?	Menene launin rumfar?
2397109	What color are the traffic lights?	Menene launin futulun zirga-zirga.
2357684	What are the horses standing on?	Me dawakan suke tsaye akai?
2375798	What is the person walking on?	Me mutumin yake tafiya a kai?
2378366	What colors are the blanket?	Wasu launika a jikin bargon?
2363014	Where is the nose?	Ina hancin?
2376332	What item is near the shore?	Wanne abu ne ke kusa da gaɓa ruwa?
2387827	How man men are in the picture?	Maza nawa na a hoton?
2318683	What color are the curtains?	Mene launin labulen?
2337237	What color is the floor?	Mene launin ƙasan daɓan?
2412914	How many people are there?	Mutane nawa ne a nan?
2374619	Who is in the picture?	Waye a hoton?
2334471	What is red?	Mene Ja?
2361225	Where was the picture taken?	A ina aka ɗauki hoton?
2357684	What is in the background?	Mene a kasan bayan hoton?
2402216	What other person can be seen?	Wanne mutumin ake iya gani kuma?
2334271	What is the man sitting on?	A kan me mutumin ke zaune?
2334271	How many bikes do you see?	Babur nawa kake iya gani?
2399248	What is the room?	Ɗakin mene ne?
2368617	Where is the carpet?	Ina kafet din?
2396341	What fruit is on the white plate on the table?	Wanne kayan marmari ne a kan farin faranti akan tebur?
2332982	When was this image taken?	Yaushe aka ɗauka wannan hoton?
2355145	What is behind the sink counter top?	Menene a bayan saman kantar sink ɗin?
2318683	Who is with the man?	Waye tare da mutumin?
2361344	What are the women eating?	Me matan suke ci?
2335754	What color are the leaves outside?	Wani launi ne da ganyanyakin dake waje?
2379559	What kind of animal is this?	Wacce irin dabba ce wannan?
2402203	What are the fluffy things in the sky?	Wasu abubuwa masu laushi ne a sama?
2358603	How many machines are there?	Nawane adadin na'urori a gurin?
2362259	What shade are the majority of the bricks on the building?	Wani launi ne da yawancin bulo ɗin ginin?
2362259	What is in the black containers?	Menene a cikin baƙaƙen mazubin?
2374619	What are the door handles on the refrigerator made of?	Da me aka yi mariƙin ƙofar a jikin firjin?
2370181	What type of bread is shown?	Wani irin biredi aka nuna?
2343297	What color are the leaves on flowers?	Wani launi ne da ganyanyakin jikin furannin?
2413695	What is behind the giraffes?	Menene a bayan raƙuman dawan?
2344495	What type of ground is there?	Wani irin ƙasa ne a gurin?
2378808	How wheels does the vehicle have?	Nawa taya abin hawan yake da shi?
2375798	What is the man in front of?	A gaban me mutumin yake?
2324913	What food tops the dish in the foreground?	Wani abinci ne a saman haɗin abincin a gaban?
2411351	Who is on the man's shirt?	Waye a jikin rigar mutumin?
2334271	What color is the bike?	Wani launi ne da babur ɗin?
2334271	What is the man holding?	Me mutumin yake riƙe dashi?
2362649	What are the walls made of?	Da me akayi bangon?
2365624	How many cows in the fence?	Nawane adadin saniyoyi a cikin shingen?
2389565	What does the woman have around her neck?	Me matar take da shi zagaye da wuyan ta?
2407122	What time of day?	Wani lokacin rana?
2411997	What color is the helmet?	Wani launi ne da hular kwanon?
2338114	What is in the background of the picture?	Menene a bayan hoton?
2410830	When was this pic taken?	Yaushe aka ɗauka hoton?
2408406	What is the color of the water?	Menene launin ruwan?
2368617	Where is the bed?	Ina gadon?
2368617	What is the sunlight shining through?	Ta cikin ina hasken ranar yake haskowa?
2399850	How is the hair done?	Yaya aka gyara gashin?
2352961	How many flower arrangements can you see?	Nawa ne adadin gyaran furanni da ka iya gani?
2396341	Who is holding a helmet?	Waye riƙe da hular kwano?
2374977	What is floral and white?	Menene mai furanni kuma fari?
2318638	Who has the surfboard?	Waye yake da allon hawan igiyar ruwan?
2332982	How many people are shown?	Nawane adadin mutanen da aka nuna?
2355145	What color is the sink?	Wani launi ne da sink ɗin?
2359279	What color are the towels?	Wani launi ne da tawul ɗin?
2361344	How the hot dog holding?	Yaya riƙewan Hot dog ɗin?
2402203	Where was the picture taken?	A ina aka ɗauka hoton?
2362601	What is the man doing?	Me mutumin yake yi?
2358603	Who is in the picture?	Waye a cikin hoton?
2359580	What is the sidewalk and street made of?	Da me akayi gefen hanyan da titin?
2372344	Where are the parked cars?	Ina ajiyayyun motocin?
2410531	What is photo of?	Hoton menene?
2353356	What color is the chair?	Wani launi ne da kujerar?
2353356	How many people are in this picture?	Nawane adadin mutane a cikin wannan hoton?
2343297	What color is the tablecloth?	Wani launi ne da ƙyallen tebur ɗin?
2346879	What city is this?	Wani birni ne wannan?
2357684	When was this photo taken?	Yaushe aka ɗauka wannan hoton?
2354144	What company runs the bus?	Wani kamfani ne ke tafiyar da bas ɗin?
2402216	What type of shirt is the man wearing?	Wace irin riga mutumin yake sanye da ita?
2342125	Who is looking directly at the photographer?	Waye ke kallon mai hoton kai tsaye?
2367980	What is on the other side of the lake?	Mene a ɗayan gefen tafkin?
2334365	How many people?	Mutane nawa?
2416681	What color are the leaves?	Mene launin ganyayyakin?
2395872	What is the girl holding a right hand?	Me yarinyar ke riƙe dashi a hannun dama?
2395872	Where is the girl standing?	Ina yarinyar ke tsaye?
2398614	How is the dog?	Ya karen yake?
2316928	What color is the water?	Mene launin ruwan?
2334471	Where is a kite?	Ina jirgin ledar?
2353356	What type of animal is that?	Wanne irin dabba waccan?
2346879	How many mirrors are visible?	Madubi nawa ake gani?
2361117	What is the man wearing?	Me mutumin ke sanye dashi?
2338114	Where is the skateboard?	Ina allon sulun ƙanƙara?
2328298	Where was the photo taken?	A ina aka ɗauki hoton?
2367980	When was this picture taken?	Yaushe aka ɗauka hoton?
2367980	How many benches are there?	Benci nawa ne a nan?
2399850	What is the bed beside?	A gefen me gadon yake?
2336041	What is in the sky?	Ina ne a sararin samaniya?
2352961	Where are the flowers?	Ina furannin?
2374734	Where is the light?	Ina fitular?
2416681	When was the picture taken?	Yaushe aka ɗauka hoton?
2408813	What color is the grass?	Wani launi ne da ciyawan?
2387827	What is the man doing that's standing in the photo?	Me mutumin dake tsaye yake yi dake cikin hoton .
2337237	Where is the dog?	Ina karen?
2379559	What color is the cat's back flank?	Wani launi ne da bayan kwankwason magen?
2370181	What color is the tablecloth on the table?	Mene launin mayafin tebur in dake kan tebur?
2359450	What is in front of the buses?	Menene a gaban bas ɗin?
2344495	What kind of animal is there?	Wanne irin dabba ce a nan?
2397109	What color is the statue?	Wani launi ne da gunkin?
2402216	What race is the boy?	Wanne kabila ne yaron?
2338114	What is the boy doing in the picture?	Me yaron yake yi a cikin hoton?
2363014	Where is the eye?	Ina idon?
2414214	What types of food are these?	Wasu irin abinci ne wa'ennan?
2399850	Where is the boy's index finger?	Ina yatsan nunin yaron?
2336041	How does the plane fly?	Ta yaya jirgin saman yake tashi?
2407281	Where is the man?	Ina mutumin?
2323128	What colors are the street lines?	Wasu launuka ne da layukan titin?
2323128	What is in the background?	Menene a bayan?
2334365	Where is black dress?	Ina baƙar rigar?
2402657	What can be seen outside the vehicle?	Menene ake iya gani a wajen abun hawan?
2395872	Who is in the picture?	Waye a cikin hoton?
2340279	What spicy vegetable is a topping?	Wani ganye mai yaji ne a saman?
2332982	What color is the man's goggles?	Wani launi ne da gogul ɗin mutumin?
2345486	Where is this picture taken?	A ina aka ɗauki wannan hoton?
2337237	Who is in the photo?	Waye a hoton?
2353318	What is hanging from the woman's ear?	Meye rataye a kunnan matar?
2353318	What color is the plate?	Mene launin farantin?
2338538	What is the color of the sky?	Mene launin sararin samaniya ?
2333489	Where is the stove?	Ina murhun?
2354144	Where is the bus?	Ina bas ɗin?
2361117	Where is the door?	Ina ƙofar?
2411351	What is shading the man?	Menene ya rufe mutumin?
2325842	How many kites are there?	Nawane adadin jiragen leda a gurin?
2365624	What is on the ground?	Menene a ƙasa?
2367360	Where is the wool?	Ina gashin tunkiyan?
2378366	How many brown cats?	Nawane adadin maguna ruwan ƙasa?
2378366	How many cats?	Nawane adadin mage?
2378366	What color is the grass?	Wani launi ne da ciyawan?
2411997	What color are the numbers in the motorcyclist?	Wani launi ne da lambobin jikin mai tuƙin babur ɗin?
2408406	What is the boat made of?	Da me akayi kwalekwalen?
2342125	How many people are in the picture?	Nawane adadin mutane a cikin hoton?
2342125	Where are the children?	Ina yaran?
2399850	How does the boy's forehead look?	Kamar yaya goshin yaron yayi?
2399850	Where was the picture taken?	A ina aka ɗauka hoton?
2407281	What is the man holding?	Me mutumin yake riƙe dashi?
2323128	Who is pulling the cart?	Waye yake jan amalanken?
2402829	What's the color of the water?	Menene launin ruwan?
2401945	What sport is the boy playing?	Wanne wasa yaron yake yi?
2332982	What sport is the man doing?	Wani wasa mutumin yake yi?
2318683	When was the photo taken?	Yaushe aka ɗauki hoton?
2345486	What color is the train?	Mene launin jirgin ƙasa?
2336292	Where was the photo taken?	A ina aka ɗauka hoton?
2380355	When is the photo taken?	Da yaushe aka ɗauki hoton ?
2338538	What is the man wearing?	Me mutumin yake riƙe dashi?
2370181	What is on the plate?	Mene akan farantin?
2375798	What is the man holding?	Me mutumin yake riƙe dashi?
2367360	What are the sheep doing?	Me tunkiyoyin ke yi?
2336041	Where is the plane from?	Daga ina jirgin saman yake?
2374977	What number of men are eating?	Mutane nawa ke cin abinci?
2402657	What animal is shown?	Wacce dabba ake gani?
2340279	How many fingers are showing?	Yatsu nawa ake gani?
2316928	When was the picture taken?	A yaushe aka ɗauki hoton?
2378578	What is on the woman's face?	Mene a fuskar matar?
2336868	How many people are clearly visible?	Mutane nawa ake iya gani sosai?
2402203	Where are the street signs?	Ina alamar titi?
2336292	What sport is being played?	Wanne wasa aka bugawa?
2360930	What is in the image?	Menene a jikin hoton?
2343297	How are the flowers arranged?	Yaya aka shirya furannin?
2343297	What color are the flowers?	Wana launi ne furran?
2346879	What color is the road?	Wana launi ce hanyar?
2378808	Where is the man riding?	A ina mutumin yake tuƙi?
2324913	What items are displayed here?	Waɗanna abubuwa ne aka nuna a nan?
2324913	What seafood item is part of the dish on the left?	Wana abincin ruwa ne ke cikin abincin dake ɓarin hagu?
2334271	Who is he pointing to?	Wa yake nunawa?
2362649	What is in the glasses?	Menene acikin gilasan?
2410830	Where is the truck parked?	A ina aka ajiye tankar?
2363154	What is the main color of the road sign?	Menene babbar launin  alamar hanyar?
2414214	How many oranges are shown?	Lemuka nawa aka nuna?
2377223	What is on the woman's t-shirt?	Menene akan tishit din matan?
2345589	When was this photo taken?	Yaushe aka ɗauki wannan hoton?
2335754	What type of animal is in the picture?	Wana irin dabba ne ajikin hoton?
